### ISSUE TITLE
Cluster crash on send

### ISSUE THREAD

**Issue by aristotelis-vryonidis** [FinalZJY/SharedMemory#2]
Race condition when a worker exits (crashes or normal exit) and the manager calls **target.send(msg);** (lines 68 and 80).

`events.js:353
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:712:16)
    at Worker.send (internal/cluster/worker.js:46:10)
    at /snapshot/tmp/node_modules/cluster-shared-memory/src/manager.js:68:16
    at /snapshot/tmp/node_modules/cluster-shared-memory/src/manager.js:95:15
    at new Promise (<anonymous>)
    at /snapshot/tmp/node_modules/cluster-shared-memory/src/manager.js:94:13
    at Array.map (<anonymous>)
    at Manager.notifyListener (/snapshot/tmp/node_modules/cluster-shared-memory/src/manager.js:92:19)
    at /snapshot/tmp/node_modules/cluster-shared-memory/src/manager.js:118:14
    at new Promise (<anonymous>)
Emitted 'error' event on Worker instance at:
    at ChildProcess.<anonymous> (internal/cluster/worker.js:30:12)
    at ChildProcess.emit (events.js:376:20)
    at internal/child_process.js:716:35
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
` 

Should adding try/catch on .send fix this?

**Comment by FinalZJY** [comment]
I fixed it in v1.1.4 by checking `target.isConnected()` before calling `target.send(msg)`. More detail in [commit 6438969](https://github.com/FinalZJY/cluster-shared-memory/commit/64389698f01e5222b4ce95303338b939da7c8520)
